// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NovaWallet.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NovaWallet.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NovaWalletDbContext))]
    [Migration("20260918105415_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NovaWallet.Domain.Auditing.AuditLogEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Actor")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("actor");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_kobo");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_kobo");

                    b.Property<long>("BalanceBefore")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_before_kobo");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("correlation_id");

                    b.Property<int>("EventType")
                        .HasColumnType("integer")
                        .HasColumnName("event_type");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("CorrelationId")
                        .HasDatabaseName("ix_audit_logs_correlation_id");

                    b.HasIndex("WalletId", "OccurredAtUtc")
                        .HasDatabaseName("ix_audit_logs_wallet_occurred");

                    b.ToTable("audit_logs", (string)null);
                });

            modelBuilder.Entity("NovaWallet.Domain.Ledger.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint")
                        .HasColumnName("amount_kobo");

                    b.Property<long>("BalanceAfter")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_after_kobo");

                    b.Property<int>("Direction")
                        .HasColumnType("integer")
                        .HasColumnName("direction");

                    b.Property<string>("Narration")
                        .HasMaxLength(140)
                        .HasColumnType("character varying(140)")
                        .HasColumnName("narration");

                    b.Property<DateTime>("OccurredAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at_utc");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("reference");

                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.HasKey("Id");

                    b.HasIndex("Reference")
                        .HasDatabaseName("ix_ledger_entries_reference");

                    b.HasIndex("WalletId", "OccurredAtUtc")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_ledger_entries_wallet_occurred");

                    b.ToTable("ledger_entries", (string)null);
                });

            modelBuilder.Entity("NovaWallet.Domain.Wallets.Wallet", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<long>("Balance")
                        .HasColumnType("bigint")
                        .HasColumnName("balance_kobo");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("customer_id");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_wallets_customer_id");

                    b.ToTable("wallets", null, t =>
                        {
                            t.HasCheckConstraint("ck_wallets_balance_non_negative", "balance_kobo >= 0");
                        });
                });

            modelBuilder.Entity("NovaWallet.Infrastructure.Persistence.Entities.DailyTransferTotal", b =>
                {
                    b.Property<Guid>("WalletId")
                        .HasColumnType("uuid")
                        .HasColumnName("wallet_id");

                    b.Property<DateOnly>("WatDate")
                        .HasColumnType("date")
                        .HasColumnName("wat_date");

                    b.Property<long>("TotalSentKobo")
                        .HasColumnType("bigint")
                        .HasColumnName("total_sent_kobo");

                    b.HasKey("WalletId", "WatDate");

                    b.ToTable("daily_transfer_totals", null, t =>
                        {
                            t.HasCheckConstraint("ck_daily_totals_non_negative", "total_sent_kobo >= 0");
                        });
                });

            modelBuilder.Entity("NovaWallet.Infrastructure.Persistence.Entities.IdempotencyRecord", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("text")
                        .HasColumnName("response_body");

                    b.Property<int?>("ResponseStatusCode")
                        .HasColumnType("integer")
                        .HasColumnName("response_status_code");

                    b.Property<int>("State")
                        .HasColumnType("integer")
                        .HasColumnName("state");

                    b.HasKey("Key");

                    b.ToTable("idempotency_records", (string)null);
                });

            modelBuilder.Entity("NovaWallet.Domain.Ledger.LedgerEntry", b =>
                {
                    b.HasOne("NovaWallet.Domain.Wallets.Wallet", null)
                        .WithMany()
                        .HasForeignKey("WalletId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
